version: 2
updates:
  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "FranciscoGarralda"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      next-dependencies:
        patterns:
          - "next"
          - "@next/*"
      react-dependencies:
        patterns:
          - "react"
          - "react-*"
    
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "FranciscoGarralda"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      express-dependencies:
        patterns:
          - "express"
          - "express-*"
      security-dependencies:
        patterns:
          - "helmet"
          - "bcryptjs"
          - "jsonwebtoken"
    
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "FranciscoGarralda"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"